server:
  port: 8081

eureka:
  instance:
    hostname: cloud00
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://cloud02:8083/eureka/,http://cloud01:8082/eureka/

spring:
  cloud:
    config:
      discovery:
        enabled: true