server:
  port: 8081

eureka:
  instance:
    hostname: cloud
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://cloud:${server.port}/eureka/

spring:
  cloud:
    config:
      discovery:
        enabled: true