server:
  port: 4001

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8081/eureka/
  instance:
    preferIpAddress: false
    hostname: cloud

ribbon:
  eureka:
    enabled: true
#配置路由规则
zuul:
  routes:
    api:
      path: /user/**
      serviceId: userservice
    ribbon:
      path: /ribbon/**
      serviceId: consumerservice
    feign:
      path: /feign/**
      serviceId: feign
