server:
  port: 4001

eureka:
  client:
    serviceUrl:
      defaultZone: http://cloud:8081/eureka/
  instance:
    preferIpAddress: false
    hostname: cloud

ribbon:
  eureka:
    enabled: true
#配置路由规则
zuul:
  routes:
    api:
      path: /api/**
      serviceId: userservice
