server:
  port: 8083

eureka:
  instance:
    hostname: cloud02
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://cloud00:8081/eureka/,http://cloud01:8082/eureka/

spring:
  cloud:
    config:
      discovery:
        enabled: true