server:
  port: 8082

eureka:
  instance:
    hostname: cloud01
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://cloud00:8081/eureka/,http://cloud02:8083/eureka/

spring:
  cloud:
    config:
      discovery:
        enabled: true