---
server:
  port: 7001

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8081/eureka/
  instance:
    preferIpAddress: false
    hostname: cloud
spring:
  profiles: userservice0

ribbon:
  eureka:
    enabled: true
---
server:
  port: 7002

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer3:8083/eureka/
  instance:
    preferIpAddress: false
    hostname: cloud
spring:
  profiles: userservice1

ribbon:
  eureka:
    enabled: true